# Global Config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
 
# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
 
rule_files:
  - "alert.rules"
 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']

  # - job_name: 'DEV'
  #   file_sd_configs:
  #     - files:
  #        - dev-targets.yml
          
  # - job_name: 'PROD'
  #   file_sd_configs:
  #     - files:
  #        - prod-targets.yml
